### PR TITLE
Feature request - https://github.com/vtex-apps/store-discussion/issues/485

### PR DESCRIPTION
**Pull request by oviolion**
#### What problem is this solving?

Considering the following piece of code from the `store-theme` project
```json
  "modal-trigger#add-to-cart": {
        "props": {
          "customPixelEventName": "addToCart"
        },
        "children": [
          "modal-layout#add-to-cart"
        ]
      },
      "modal-header#add-to-cart": {
        "props": {
          "showCloseButton": true,
          "iconCloseSize": 20
        },
        "children": [
            "rich-text#add-to-cart"
        ]
      },
      "rich-text#add-to-cart": {
        "props": {
          "textAlignment": "LEFT",
          "textPosition": "LEFT",
          "text": "Produsul a fost adaugat in cos"
        }
      },
      "modal-layout#add-to-cart": {
        "children": [
          "modal-header#add-to-cart",
          "flex-layout.row#bought-product",
          "shelf.relatedProducts"
        ],
        "props": {
            "customPixelEventId": "addToCart"
          }
      },
      "flex-layout.row#bought-product":{
        "children": [
          "vtex.store-components:product-name",
          "product-description-short",
          "product-price-extended",
          "flex-layout.row#buy-button"
        ]
      }
```

## Before
When the `modal-trigger#add-to-cart` is added inside the `store.product` block, it will have the following behavior -
UniConverter_20201119144017

But when you add the `modal-trigger#add-to-cart` to the category page, or in any list of products, it will obviously have the following behavior (as the `modal-trigger` block is added for each product in the list) - 
<br />
UniConverter_20201119144902

#### Screenshots or example usage:
UniConverter_20201125115631

#### How to test it?

[Workspace](https://devs--fstudio.myvtex.com/canon-eos-4000d-kit-ef-s-18-55mm-f-3-5-5-6-iii/p)

#### Related to / Depends on

[Issue Link](https://github.com/vtex-apps/store-discussion/issues/485)

### CODE REVIEW

**Comment by victorhmp** [comment]
Hi @oviolion!

Sorry for the delay, but I've already taken a look at this PR and I'm discussing this solution with the rest of the team so that I can provide you a single review with all proposed changes at once :)

**Comment by oviolion** [comment]
> Hi @oviolion!
> 
> Sorry for the delay, but I've already taken a look at this PR and I'm discussing this solution with the rest of the team so that I can provide you a single review with all proposed changes at once :)

That's perfect, thank you!

**Comment by victorhmp** [comment]
Hi @oviolion!

It seems the solution I've described to you in https://github.com/vtex-apps/store-discussion/issues/485 already solves this issue. We just need to implement a tiny change in `vtex.add-to-cart-button` to enable you to disable this guy right [here](https://github.com/vtex-apps/add-to-cart-button/blob/master/react/AddToCartButton.tsx#L168).

Anyway, to achieve the behavior you want, there's no need to mess with pixel events. You just need to use the same solution implemented in our [`store-theme`](https://github.com/vtex-apps/store-theme/blob/master/store/blocks/product-summary/quickview.json). Over there we implemented a `quickview`, but the idea is the same.

You would just need to change this [line](https://github.com/vtex-apps/store-theme/blob/master/store/blocks/product-summary/quickview.json#L4) to `"add-to-cart-button"`. Then you would have a `modal-trigger` around each `add-to-cart-button` on the page. Each one is totally independent, so nothing strange should happen :)

**Comment by victorhmp** [comment]
@oviolion I'm closing this PR since we're only going to add a new prop to the `add-to-cart-button` block :)

**Pull request closed without merging**
