### PR TITLE
Fix: handleKeyDown function to properly handle Escape key when disableEscapeKeyDown is true

### PR DESCRIPTION
**Pull request by leitecsleite**
#### What problem is this solving?

Fix handleKeyDown function to properly handle Escape key when disableEscapeKeyDown is true

#### How to test it?

[Workspace](https://task10157--motobr.myvtex.com/capacete-ls2-ff320-stream-loop-preto-vermelho/p)

#### Screenshots or example usage:

https://www.loom.com/share/898f952fb0df4e1ca39a8d72dcc5ef7c

### CODE REVIEW

**Comment by leitecsleite** [comment]
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

**Comment by leitecsleite** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by iago1501** [comment]
Hi @leitecsleite thanks for collaborating with that.

Just some questions: 

What's the problem that we are trying to fix here? When using `esc` to close the modal and the prop disableEscapeKeyDown is set as true, it's closing the modal?

To test that we just need to open the modal and try to close it with esc? Can I test the same behavior in [master workspace](https://master--motobr.myvtex.com/capacete-ls2-ff908-strobe-2-orion-fosco-preto-roxo/p), for example?

**Comment by iago1501** [comment]
Closing this PR due to lack of evidence, in case of any changes feel free to open the PR again 👋🏻

**Pull request closed without merging**
